### ISSUE TITLE
Resource Monitor Disappears when you setup / use CAN BUS

### ISSUE THREAD

**Issue by JesNoFear** [Renaud11232/OctoPrint-Resource-Monitor#42]
The plugin disappears from  Settings -> Plugins and from the tab after setting up CANBOOT
Still shows up in Plugin Manager.

I did uninstall it and reinstall it, thinking it may have gotten corrupted but no dice.

I was curious the amount of data being sent over CAN0, then noticed the tab was missing.

**Comment by Renaud11232** [comment]
Hello,

Can you put the plugin logging level to `DEBUG` in the settings and upload the logs here.

Thanks

**Comment by JesNoFear** [comment]
Do you have a way to change the log level via command line or editing a file, as the plugin no longer shows up in the plugins tab.

![Screenshot_20230214-053210.png](https://user-images.githubusercontent.com/51521144/218710571-fc427f62-550d-4080-9860-51a74abdab20.png)

![Screenshot_20230214-053134.png](https://user-images.githubusercontent.com/51521144/218710588-5744e98c-019f-4233-8aa4-dd00f83b1209.png)

**Comment by Renaud11232** [comment]
Hello,

You can set the logging level from OctoPrint's Logging settings page : If possible, you need to add a log level configuration for `octoprint.plugins.resource_monitor` (not the one ending with `.profiling`) with the `DEBUG` level.

![image](https://user-images.githubusercontent.com/13933802/219841038-2a44c022-2d15-4cb0-88c2-627377268413.png)

Then, from the same page, you can download `octoprint.log` and upload it here.

Sorry if this wasn't clear

Thanks

**Comment by JesNoFear** [comment]
[octoprint.log](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/files/10787876/octoprint.log)

it looks unhappy on line 1547

is it because it see's can0 as an interface without a address on it?

**Comment by Renaud11232** [comment]
Hello,

The error occurs because `psutil.net_if_addrs()` did not return any address for that interface.
However I had already released a prerelease that adresses this issue but did not publish it on the main branch.

Can you try to install version `0.3.12rc1` of the plugin using this URL : https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/refs/tags/0.3.12rc1.zip
You need to go to the OctoPrint Settings > Plugin Manager > + Get more > from URL and use the URL above.

If that solves the issue, I'll release this.

Thanks

**Comment by JesNoFear** [comment]
That worked.

![image](https://user-images.githubusercontent.com/51521144/220803441-3017d5a4-d11b-4596-9181-cfa3e213cecb.png)

Thank you

**Comment by Renaud11232** [comment]
Hello,
I just released this into `0.3.12` as a normal (non prerelease) update.

Thanks for your help
